import turtle

gun = turtle.Turtle()
turtle.bgcolor("black")
gun.color("yellow")


def rect():
    gun.pensize(9)
    gun.forward(170)
    gun.left(45)
    gun.forward(6)
    gun.left(45)
    gun.forward(170)
    gun.left(45)
    gun.forward(6)
    gun.left(45)
    gun.forward(330)
    gun.left(45)
    gun.forward(6)
    gun.left(45)
    gun.forward(170)
    gun.left(45)
    gun.forward(6)
    gun.left(45)
    gun.forward(170)

def four_corner_lines():
    gun.pensize(12)
    gun.penup()
    gun.forward(180)
    gun.left(90)
    gun.forward(35)
    gun.left(90)
    gun.pendown()
    gun.forward(12)
    gun.penup()
    gun.forward(344)
    gun.pendown()
    gun.forward(17)
    gun.penup()
    gun.right(90)
    gun.forward(105)
    gun.right(90)
    gun.pendown()
    gun.forward(17)
    gun.penup()
    gun.forward(344)
    gun.pendown()
    gun.forward(12)

def P():
    gun.penup()
    gun.left(180)
    gun.forward(280)
    gun.pendown()
    gun.forward(40)
    gun.left(90)
    gun.forward(100)
    gun.left(180)
    gun.forward(52)
    gun.right(90)
    gun.forward(40)
    gun.left(90)
    gun.forward(47)

def U():
    gun.penup()
    gun.right(90)
    gun.forward(32)
    gun.right(90)
    gun.pendown()
    gun.forward(98)
    gun.left(90)
    gun.forward(40)
    gun.left(90)
    gun.forward(98)

def B(): 
    gun.penup()
    gun.right(90)
    gun.forward(35)
    gun.pendown()
    gun.forward(45)
    gun.right(90)
    gun.forward(43)
    gun.right(45)
    gun.forward(5)
    gun.right(45)
    gun.forward(40)
    gun.left(90)
    gun.forward(5)
    gun.left(90)
    gun.forward(40)
    gun.right(45)
    gun.forward(5)
    gun.right(45)
    gun.forward(40)
    gun.right(90)
    gun.forward(45)
    gun.right(90)
    gun.forward(96)

def G():
    gun.penup()
    gun.right(180)
    gun.forward(53)
    gun.left(90)
    gun.forward(98)
    gun.pendown()
    gun.forward(25)
    gun.right(90)
    gun.forward(45)
    gun.right(90)
    gun.forward(45)
    gun.right(90)
    gun.forward(95)
    gun.right(90)
    gun.forward(40)

rect()
four_corner_lines()
P()
U()
B()
G()
turtle.done()